1

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,31 +1,23 @@
 #!/bin/sh
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
-if [[ "$STAGED_FILES" = "" ]]; then
-  exit 0
+#
+# Run JSHint validation before commit.
+files=$(git diff HEAD --name-only --diff-filter=ACMR -- static/mobile/**.js)  
+pass=true
+if [ "$files" != "" ]; then  
+    for file in ${files}; do
+        result=$(jshint ${file})
+        if [ "$result" != "" ]; then
+            echo "$result"
+            echo "\n"
+            pass=false
+        fi
+    done
 fi
-PASS=true
-echo "\nValidating Javascript:\n"
-# Check for eslint
-which eslint &> /dev/null
-if [[ "$?" == 1 ]]; then
-  echo "\t\033[41mPlease install ESlint\033[0m"
-  exit 1
-fi
-for FILE in $STAGED_FILES
-do
-  eslint "$FILE"
-  if [[ "$?" == 0 ]]; then
-    echo "\t\033[32mESLint Passed: $FILE\033[0m"
-  else
-    echo "\t\033[41mESLint Failed: $FILE\033[0m"
-    PASS=false
-  fi
-done
-echo "\nJavascript validation completed!\n"
-if ! $PASS; then
-  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
-  exit 1
-else
-  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-fi
-exit $?
+if $pass; then  
+    exit 0
+else  
+    echo ""
+    echo "COMMIT FAILED:"
+    echo "Some JavaScript files are invalid. Please fix errors and try committing again."
+    exit 1
+fi 
